### ISSUE TITLE
Implement custom headers based on route

### ISSUE THREAD

**Issue by 70m3n** [MartinLG/nuxt-custom-headers#2]
I use a base component which is resolved on every route. I use custom headers here and would like to use a route's meta to set different cache-control on some routes. Therefore, I'd like the Nuxt context to be passed into httpHeaders, like this:

```
httpHeaders: (context) => ({
    'Cache-Control': `max-age=${context.app.router.currentRoute.meta.cache}, public`
}),
```

Is this doable?

**Comment by MartinLG** [comment]
Yes I think, I will try to work on it tonight

**Comment by MartinLG** [comment]
This feature has been added to the 2.1.0 release :)
https://www.npmjs.com/package/nuxt-custom-headers

Thanks for the suggestion.

**Comment by 70m3n** [comment]
Nice work!

Thank you very much. :)
